### ISSUE TITLE
Diff always produces results as if creating the stack fresh

### ISSUE THREAD

**Issue by mrchops1024** [AndrewChubatiuk/serverless-diff-plugin#3]
Before deploying the initial package, the diff shows me all the resources that are going to be deployed. After fully deploying the stack and running the diff again, it continues to show me that all resources need to be created. If I make a change (such as an IAM policy), instead of showing me the change the report shows deploying all resources. Here is a minimum sample I can replicate the issue with:

```yml
service: serverless-diff-plugin-test

frameworkVersion: '3'

plugins:
  - serverless-diff-plugin

package:
  individually: true

custom:
  app_name: serverless-diff-plugin-test
  dev:
    env_abbr: d
    env_name: Development
  prod:
    env_abbr: s
    env_name: Production
  region_abbr:
    us-west-2: usw2
  diff:
    reportPath: ./diff.json

provider:
  name: aws
  runtime: python3.11
  region: us-west-2
  stackName: cfn-stack-${self:custom.region_abbr.${aws:region}}-${self:custom.app_name}-${self:custom.${sls:stage}.env_abbr}
  deploymentBucket:
    name: prefix-${self:custom.region_abbr.${aws:region}}-${self:custom.app_name}-${self:custom.${sls:stage}.env_abbr}
    maxPreviousDeploymentArtifacts: 5

resources:
  Resources:
    resourceSchedulerLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/lambda-${self:custom.region_abbr.${aws:region}}-${self:custom.app_name}-${self:custom.${sls:stage}.env_abbr}
        RetentionInDays: 30
    resourceSchedulerRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        RoleName: prefix-role-${self:custom.app_name}-${self:custom.${sls:stage}.env_abbr}
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: sts:AssumeRole
              Principal:
                Service:
                  - lambda.amazonaws.com
        Policies:
          - PolicyName: prefix-policy-${self:custom.app_name}-${self:custom.${sls:stage}.env_abbr}
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'logs:CreateLogGroup'
                    - 'logs:CreateLogStream'
                    - 'logs:PutLogEvents'
                  Resource: '*'
```
